-   id: pyright
    name: pyright
    entry: pyright
    language: node
    pass_filenames: false
    types: [python]
    args: []
    require_serial: false
    additional_dependencies: ["pyright@1.1.170"]
