-   id: pyright
    name: pyright
    entry: pyright
    language: node
    'types': [python]
    args: []
    require_serial: false
    additional_dependencies: ["pyright@1.1.179"]
    minimum_pre_commit_version: '0'
