name: main
on:
  push:
    branches: [main]
  schedule:
    - cron: "15 8 * * *"

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pre-commit-mirror-maker
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: pre-commit-mirror . --language=node --package-name=pyright --types=python --entry='pyright' --id=pyright
      - run: git push origin main --tags
